### ISSUE TITLE
orca no arranca o no muestra nada en max8-beta1

### ISSUE THREAD

**Issue by javierpuche** [max-linux/max-desktop#746]
Probado en 64 bits, en consola muestra:  (¿alguna librería de python o path?)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/orca/generator.py", line 242, in generate
    result = eval(formatting, globalsDict)
  File "<string>", line 1, in <module>
NameError: name 'displayedText' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/orca/generator.py", line 256, in generate
    globalsDict[arg] = self._methodsDict[arg](obj, **args)
  File "/usr/lib/python3/dist-packages/orca/generator.py", line 944, in _generateDisplayedText
    displayedText = self._script.utilities.displayedText(obj)
  File "/usr/lib/python3/dist-packages/orca/script_utilities.py", line 611, in displayedText
    if not displayedText and obj.parent.getRole() == pyatspi.ROLE_LIST_BOX:
AttributeError: 'NoneType' object has no attribute 'getRole'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/orca/generator.py", line 242, in generate
    result = eval(formatting, globalsDict)
  File "<string>", line 1, in <module>
NameError: name 'labelAndName' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/orca/generator.py", line 256, in generate
    globalsDict[arg] = self._methodsDict[arg](obj, **args)
  File "/usr/lib/python3/dist-packages/orca/generator.py", line 342, in _generateLabelAndName
    name = self._generateName(obj, **args)
  File "/usr/lib/python3/dist-packages/orca/scripts/apps/gnome-panel/speech_generator.py", line 59, in _generateName
    _generateName(self, obj, **args)
  File "/usr/lib/python3/dist-packages/orca/speech_generator.py", line 155, in _generateName
    result = generator.Generator._generateName(self, obj, **args)
  File "/usr/lib/python3/dist-packages/orca/generator.py", line 303, in _generateName
    name = self._script.utilities.displayedText(obj)
  File "/usr/lib/python3/dist-packages/orca/script_utilities.py", line 611, in displayedText
    if not displayedText and obj.parent.getRole() == pyatspi.ROLE_LIST_BOX:
AttributeError: 'NoneType' object has no attribute 'getRole'

**Comment by javierpuche** [comment]
instalar speech-dispatcher  (también vemos que edubuntu lleva atspi-qt)
