### ISSUE TITLE
MAX 9.5. Reempaquetar Arasuite. Reabierto, no va GalleryApp y actualizar a 2_2_4

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#783]
Se sigue usando esta suite para atender a alumnos con necesidades educativas especiales y con trastorno del espectro autista TEA que ahora es un tema bastante delicado puesto que se les está incluyendo en la escolarización general.

La forja esta en [https://sourceforge.net/projects/arasuite/files/](https://sourceforge.net/projects/arasuite/files/) Es un programa en java.

Se puede seguir este hilo del foro [(http://herramientas.educa.madrid.org/foros/viewtopic.php?f=3&t=3247&p=11054#p11048](http://herramientas.educa.madrid.org/foros/viewtopic.php?f=3&t=3247&p=11054#p11048) donde lo resuelvo a machetazos.

Lo ideal, un paquete debian bien diseñado.

**Comment by maxezek** [comment]
No funcionan.

madrid@max90:~$ /bin/bash -c "cd /opt/AraSuite/AraWord ; ./AraWordApp"
Error: no se ha encontrado o cargado la clase principal com.install4j.runtime.launcher.UnixLauncher

¡ojo! Java está dando por...

**Comment by maxezek** [comment]
En la versión del repositorio no se instala **/opt/AraSuite/.install4j** ni **/opt/AraSuite/uninstall**

He probado a instalar arasuite2.2-3.sh directamenet y funciona.

**Comment by maxezek** [comment]
Ahora no va GalleryApp.

Se intenta abrir pero se cierra. ¿Permisos? Parece que falta otra carpeta oculta .arasuite

Copio y pego la salida extraida por Daniel:

madrid@max90:/opt/AraSuite/GalleryManager$ ls
GalleryManagerApp  GalleryManagerApp.vmoptions  GalleryManager.jar  lang  libs
madrid@max90:/opt/AraSuite/GalleryManager$ ./GalleryManagerApp
Data base path: ../.arasuite
Configuration path: ../.arasuite/conf/conf.properties
/opt/AraSuite/GalleryManager/../.arasuite/conf
/opt/AraSuite/GalleryManager/../.arasuite/conf/conf.properties
java.io.IOException: No existe el archivo o el directorio
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at configuration.TConfiguration.checkConfigurationFile(Unknown Source)
	at configuration.TConfiguration.setProperty(Unknown Source)
	at configuration.TConfiguration.setLanguage(Unknown Source)
	at dialogs.mainFrame.<init>(Unknown Source)
	at dialogs.mainFrame$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at configuration.TConfiguration.setProperty(Unknown Source)
	at configuration.TConfiguration.setLanguage(Unknown Source)
	at dialogs.mainFrame.<init>(Unknown Source)
	at dialogs.mainFrame$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Data base path: ../.arasuite
Configuration path: ../.arasuite/conf/conf.properties
/opt/AraSuite/GalleryManager/../.arasuite/conf
/opt/AraSuite/GalleryManager/../.arasuite/conf/conf.properties
java.io.IOException: No existe el archivo o el directorio
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at configuration.TConfiguration.checkConfigurationFile(Unknown Source)
	at configuration.TConfiguration.getProperty(Unknown Source)
	at configuration.TConfiguration.getLanguage(Unknown Source)
	at dialogs.mainFrame.<init>(Unknown Source)
	at dialogs.mainFrame$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at configuration.TConfiguration.getProperty(Unknown Source)
	at configuration.TConfiguration.getLanguage(Unknown Source)
	at dialogs.mainFrame.<init>(Unknown Source)
	at dialogs.mainFrame$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
madrid@max90:/opt/AraSuite/GalleryManager$

**Comment by mariodebian** [comment]
Prueba a arrancarlo desde la HOME, me da que no puede escribir en /opt/Arasuite porque lo iniciamos desde allí.

**Comment by maxezek** [comment]
Mario Izquierdo <notifications@github.com> escribió:

> Prueba a arrancarlo desde la HOME, me da que no puede escribir en  
> /opt/Arasuite porque lo iniciamos desde allí.
>
>   —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].
>       

Esto dice Mario a lo de Arasuite. Ahora me voy un rato de casa y no  
puedo hacer pruebas. Que alguien mire, por favor.



Vínculos:
---------
[1] https://github.com/max-linux/max-desktop/issues/783#issuecomment-274326797
[2]

**Comment by mariodebian** [comment]
Después de hacer pruebas este programa escribe en su carpeta de instalación, es muy probable que no se pueda ejecutar en una instalación centralizada (mismo ejecutable para varios usuarios)

Lo retraso (no va en el DVD) para arreglarlo mas adelante.

**Comment by maxezek** [comment]
Si. Parece que tiene que crear una base de datos bajándosela desde la red una vez instalado. Pero como se mantiene en opt los permisos no son válidos para un usuario normal.

En WIndows funciona porque trabajan como administrador por defecto. ¿Les escribimos a los de Arasaac?

**Comment by maxezek** [comment]
Comento como se resuelve a pinrel:

De momento, prueba lo siguiente a partir de un correo que le mande a Fer Lisón.

Desinstala arasuite y limpia su rastro si lo hay en /opt
Instala con sudo apt install arasuite
sudo apt install arasuite
sudo mkdir /opt/AraSuite/.arasuite  (este directorio no se carga en la instalación inicial)
sudo chmod 755 -R /opt/AraSuite/.arasuite
sudo chmod 755 -R /opt/AraSuite/GalleryManager
sudo /bin/bash -c "cd /opt/AraSuite/GalleryManager; ./GalleryManagerApp"

Aquí actualiza la base de datos. debe terminar con ok.

sudo /bin/bash -c "cd /opt/AraSuite/AraWord ; ./AraWordApp"

Se ejecuta una vez araword y debe funcionar ya el sistema de pictos.

Cierra y abre

inicio > Acceso Universal > Araword

Y ya funciona o a mi me ha funcionado

**Comment by maxezek** [comment]
Comprobado con este script:

#!/bin/bash
sudo apt-get install arasuite
sudo mkdir /opt/AraSuite/.arasuite
sudo chmod 755 -R /opt/AraSuite/.arasuite
sudo chmod 755 -R /opt/AraSuite/GalleryManager
sudo /bin/bash -c "cd /opt/AraSuite/GalleryManager; ./GalleryManagerApp"
sudo /bin/bash -c "cd /opt/AraSuite/AraWord; ./AraWordApp"

En su momento hay que cerrar Gallery Manager para que entre Araword

**Comment by jrodriguezpascua** [comment]
Mensaje reportado en la lista de max por Mario del Olmo:

Para instalar Arasuite y probar os dejo mis apuntes
sudo apt-get install arasuite
Permisos 776
/opt/AraSuite/GalleryManager
/opt/AraSuite/.arasuite
 
sudo chmod 776 "nombrecarpeta"
421 421 420 Todos los permisos para el propietario y su grupo y de lectura y escritura (no ejecución) para el resto.
 
madrid@max90:/$ sudo chmod 776 /opt/AraSuite/GalleryManager

**Comment by maxezek** [comment]
Nueva situación. La versión 2_2_3 ha dejado de funcionar en MAX.

Pero **si funciona** [la arasuite2_2_4](https://sourceforge.net/projects/arasuite/files/) actualizar y corregir el problema del GalleryManager

**Comment by maxezek** [comment]
Fernando Lisón ha puesto como instalar arasuite2-2-4.sh correctamente en MAX 9. 

Lo ha hecho en el foro en este [enlace](http://herramientas.educa.madrid.org/foros/viewtopic.php?f=2&t=3394#p12373).

**Comment by mariodebian** [comment]
Al seguir los pasos se genera en /opt/AraSuite/ la carpeta oculta .arasuite que ocupa 543 MB (hay unos 10.000 archivos PNG)

¿en serio queremos un paquete deb de 500 megas?

**Comment by maxezek** [comment]
Se trata de un programa de atención a alumnado autista, TGD/TEA.  Estos alumnos utilizan los pictogramas para comunicarse con el mundo. Si debemos ofrecerlo porque sino los centros con este tipo de alumnado usarán la versión Windows.. **Nunca irá de serie sabiendo lo que ocupa y la descarga que representa pero hay que ofertarlo**.
Si hay que documentarlo de alguna manera y de advertirlo, **si se puede y no lleva mucho**, en la propia instalación.

Lo comento en la lista.

**Comment by mariodebian** [comment]
No entendía para que servía el programa y he abierto AraWord... Escribes una palabra y tienes varias imágenes que la identifican... muy potente.

Subido, actualizado a 2.2.4 con la base de datos (ocupa bastante...) 546 MB el paquete y 1,3 GB instalado (por si hay que documentarlo por ahí)

Después de pasar un optimizador de imágenes PNG he conseguido que baje a 448 MB de paquete y 1,1 GB una vez instalado.
