### ISSUE TITLE
MAX 10 prealfa: No funciona pilas engine

### ISSUE THREAD

**Issue by maxezek** [max-linux/max-desktop#929]
La salida que produce es

madrid@madrid-VirtualBox:~$ pilas
Gtk-Message: 13:22:32.762: Failed to load module "appmenu-gtk-module"
Gtk-Message: 13:22:32.763: Failed to load module "topmenu-gtk-module"
Traceback (most recent call last):
  File "/usr/bin/pilas", line 8, in <module>
    pilasengine.utils.iniciar_desde_terminal()
  File "/usr/lib/python2.7/dist-packages/pilasengine/utils/__init__.py", line 325, in iniciar_desde_terminal
    _ = pilasengine.abrir_asistente()
  File "/usr/lib/python2.7/dist-packages/pilasengine/__init__.py", line 623, in abrir_asistente
    import asistente
  File "/usr/lib/python2.7/dist-packages/pilasengine/asistente/__init__.py", line 16, in <module>
    from PyQt4 import QtWebKit
ImportError: cannot import name QtWebKit

**Comment by mariodebian** [comment]
Subida nueva versión de python-qt4 con QtWebKit activado (está marcado como deprecated)
Subido nuevo paquete de python-pilas con aceleración desactivada por defecto (activada da un segfault)
